### ISSUE TITLE
CLA bot doesn't work – missing tokens?

### ISSUE THREAD

**Issue by Ostrzyciel** [Kaszanas/SC2DatasetPreparator#26]
See #24 for an example. After fixing some of the bot's settings so that it didn't crash right away, it does not want to react to my messages to it.

My suspicion is this part:

```yaml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # the below token should have repo scope and must be manually added by you in the repository's secret
  PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
```

Were these tokens set up correctly?

See: https://github.com/contributor-assistant/github-action?tab=readme-ov-file#6-adding-personal-access-token-as-a-secret
